### ISSUE TITLE
panic byte index is out of bounds

### ISSUE THREAD

**Issue by wezm** [epilys/bb#1]
When I run `bb` on my system it panics.

**OS:** Arch Linux
**Kernel:** 5.2.11
**Device:** Del XPS 15

```
thread 'main' panicked at 'byte index 18446744073709551605 is out of bounds of `RAM 5.32 GiB/31.27 GiB`', src/libcore/str/mod.rs:2017:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:211
             at src/libstd/panicking.rs:474
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   4: rust_begin_unwind
             at src/libstd/panicking.rs:308
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   6: core::str::slice_error_fail
             at src/libcore/str/mod.rs:0
   7: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::index::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/str/mod.rs:1884
   8: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/option.rs:388
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/str/mod.rs:1884
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/str/mod.rs:1623
   9: <bb::ui::components::kernel::KernelMetrics as bb::ui::components::Component>::draw
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/string.rs:1981
             at src/ui/components/kernel.rs:295
  10: <bb::ui::components::utilities::Window as bb::ui::components::Component>::draw
             at src/ui/components/utilities.rs:201
  11: bb::ui::state::State::redraw
             at src/ui/state.rs:325
             at src/ui/state.rs:220
  12: bb::main
             at ./<::crossbeam_channel::select_macro::crossbeam_channel_internal macros>:0
  13: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by epilys** [comment]
I think 651501e prevents this sufficiently, if it happens again let me know!

**Comment by wezm** [comment]
Yep it's working now (although there's no memory bar)

![Screenshot from 2019-09-09 20-54-38](https://user-images.githubusercontent.com/21787/64525402-21cf9580-d344-11e9-9f51-32c6d8ecdbbd.png)

**Comment by epilys** [comment]
This was a wrong approach then, I'll recheck the calculations and assumptions `src/ui/components/kernel.rs` makes.
