### ISSUE TITLE
thread panic when entering tree view

### ISSUE THREAD

**Issue by deathtrip** [epilys/bb#20]
I'm running the git version from the AUR, and when i press 't' to enter tree view, i get this:

`thread 'main' panicked at 'no entry found for key', src/components/processes.rs:441:37
                                                                                      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                                                                                                                                   zsh: abort (core dumped)  bb`

And here's the stacktrace:
`

                Stack trace of thread 94680:
                #0  0x00007ff0d5aac615 raise (libc.so.6 + 0x3d615)
                #1  0x00007ff0d5a95862 abort (libc.so.6 + 0x26862)
                #2  0x000055f45c6fad37 n/a (bb + 0x68d37)
                #3  0x000055f45c6fad26 n/a (bb + 0x68d26)
                #4  0x000055f45c703196 n/a (bb + 0x71196)
                #5  0x000055f45c7030fb n/a (bb + 0x710fb)
                #6  0x000055f45c71bf2a n/a (bb + 0x89f2a)
                #7  0x000055f45c71bef4 n/a (bb + 0x89ef4)
                #8  0x000055f45c71bead n/a (bb + 0x89ead)
                #9  0x000055f45c6eb010 n/a (bb + 0x59010)
                #10 0x000055f45c6f11a2 n/a (bb + 0x5f1a2)
                #11 0x000055f45c6d4f0f n/a (bb + 0x42f0f)
                #12 0x000055f45c6c5623 n/a (bb + 0x33623)
                #13 0x000055f45c6becd9 n/a (bb + 0x2ccd9)
                #14 0x000055f45c6df98e n/a (bb + 0x4d98e)
                #15 0x000055f45c6a1663 n/a (bb + 0xf663)
                #16 0x000055f45c6a32dd n/a (bb + 0x112dd)
                #17 0x000055f45c6e0e01 n/a (bb + 0x4ee01)
                #18 0x00007ff0d5a97152 __libc_start_main (libc.so.6 + 0x28152)
                #19 0x000055f45c69b06e n/a (bb + 0x906e)

                Stack trace of thread 94682:
                #0  0x00007ff0d5b7055c recv (libc.so.6 + 0x10155c)
                #1  0x000055f45c6a1779 n/a (bb + 0xf779)
                #2  0x000055f45c6a5efd n/a (bb + 0x13efd)
                #3  0x000055f45c721535 n/a (bb + 0x8f535)
                #4  0x00007ff0d5a563e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007ff0d5b6f293 __clone (libc.so.6 + 0x100293)

                Stack trace of thread 94681:
                #0  0x00007ff0d5b5fefc __read (libc.so.6 + 0xf0efc)
                #1  0x000055f45c71e9f5 n/a (bb + 0x8c9f5)
                #2  0x000055f45c6b811c n/a (bb + 0x2611c)
                #3  0x000055f45c6a1639 n/a (bb + 0xf639)
                #4  0x000055f45c6a5db6 n/a (bb + 0x13db6)
                #5  0x000055f45c721535 n/a (bb + 0x8f535)
                #6  0x00007ff0d5a563e9 start_thread (libpthread.so.0 + 0x93e9)
                #7  0x00007ff0d5b6f293 __clone (libc.so.6 + 0x100293)`

Happens on bash and zsh, with multiple terminal emulators.

**Comment by epilys** [comment]
Hallo,

> I'm running the git version from the AUR

I'm ignorant about AUR, does "git version" mean it's the git master?

**Comment by deathtrip** [comment]
Yes, the generated package is at commit a9eb29d, which is the most recent as of writing this.

**Comment by epilys** [comment]
And does this happen as soon as you launch the app without any filters/other active modes? Does this happen everytime?

**Comment by deathtrip** [comment]
Yep, happens everytime, even if all i do is press 't' after launch.
Another panic i get is when i press 'F' to follow a process group:
`thread 'main' panicked at 'no entry found for key', src/components/processes.rs:1943:26`

**Comment by epilys** [comment]
I'm wondering if there's anything "unexpected" in your system, anything that `bb` doesn't account for... process namespaces etc. Do you run containers or anything security related?

Regardless of this, I think the correct fix is not to use array `Index`ing for PIDs but do this all with `Option`s.

**Comment by deathtrip** [comment]
I don't run containers. I have user namespaces disabled via `kernel.unprivileged_userns_clone = 0` and also have `hidepid=2` option on /proc. Can't think of anything else that could be causing this.

**Comment by epilys** [comment]
Could be `hidepid=2` then 🤔. Thanks, I will try to push a fix asap.

**Comment by deathtrip** [comment]
It doesn't happen when `/proc` is not mounted with `hidepid=2,` so i guess that's it.
